//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_1
    {
        public int müşteri_adı { get; set; }
        public System.DateTime seyahat_gidiş { get; set; }
        public System.DateTime seyahat_geliş { get; set; }
        public int kişi_sayısı { get; set; }
        public string hangi_bölgeden { get; set; }
        public string hangi_bölgeye { get; set; }
    }
}
